codecov:
  notify:
    require_ci_to_pass: yes
coverage:
  precision: 2
  round: down
  range: "80...100"

  status:
    project:
      default:
        against: parent
        target: 90%
        threshold: 1%
        if_no_uploads: success
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        against: parent
        target: auto
        threshold: 2%
        if_no_uploads: success
        if_not_found: success
        if_ci_failed: error
    changes: no