name: Move opened pull request In Dev

on:
  pull_request:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.2.4
        with:
          project: Explorers' Squad
          column: In Dev
          repo-token: ${{ secrets.GH_TOKEN }}
