name: Theia Zowe Explorer CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      theia:
        image: theiaide/theia
        # opens 3000 on the host and service container
        ports:
          - 3000:3000

    steps:
      - uses: actions/checkout@v2

      - run: npm ci
        # this test file must exist for build to succeed and unit tests depend on it
      - run: cp resources/testProfileData.example.ts resources/testProfileData.ts
      - run: npm run build
      - run: npm run lint
      - run: firefox -headless --screenshot screenshots/firefox-test.jpg http://localhost:3000/
      - name: Upload screenshot
        uses: actions/upload-artifact@v1
        with:
          name: results
          path: screenshots/firefox-test.jpg
      - run: npm run test:theia
