name: Theia Zowe Explorer CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      theia:
        image: theiaide/theia
        ports:
          - 3000:3000
        options: --init --health-cmd "curl --fail http://localhost:3000 || exit 1" --health-interval=5s --health-timeout=3s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - run: npm ci

      - name: Create test data file
        run: cp resources/testProfileData.example.ts resources/testProfileData.ts

      - run: npm run build

      - run: npm run lint

      - name: Verify Theia
        run: firefox --screenshot screenshots/firefox-test.jpg http://127.0.0.1:3000/

      - name: Upload screenshot
        uses: actions/upload-artifact@v1
        with:
          name: results
          path: screenshots/firefox-test.jpg

      - run: npm run test:theia
