name: Theia Zowe Explorer CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      theia:
        # image: heroku/nodejs-hello-world
        image: theiaide/theia
        ports:
          - 3000:3000
        options: --init
        # options: --init --health-cmd "curl --fail http://localhost:3000 || exit 1" --health-interval=10s --health-timeout=5s --health-retries 180

    steps:
      - uses: actions/checkout@v2

      - run: npm ci

      - name: Create test data file
        run: cp resources/testProfileData.example.ts resources/testProfileData.ts

      - run: npm run build

      - run: npm run lint

      - name: sleep
        run: sleep 300

      # - name: Verify Theia
      #   run: firefox --screenshot screenshots/firefox-test.jpg http://localhost:3000/

      # - name: Upload screenshot
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: results
          path: screenshots/firefox-test.jpg

      - run: npm run test:theia
